#!/bin/zsh

# General
bindkey -v

# My binaries
path=("$HOME/bin" $path)

# History Settings
export HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
export SAVEHIST=5000
export HISTSIZE=2000
setopt share_history
setopt append_history
setopt hist_ignore_dups
setopt hist_reduce_blanks

# LS
alias ll='ls -alhFG'

# Files
alias dud="du -h -d1 | sort -h | tail -r"

# FASD
eval "$(fasd --init auto)"

# FZF
zvm_after_init_commands+=('[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh')

# Vim
alias vim=nvim
alias ep="vim ~/dotfiles/ohmyzsh"
alias rp="source ~/dotfiles/ohmyzsh"

# Docker
alias dkc="docker-compose"
alias dkr="docker-compose run"
function dke() {
  if [[ $1 = psql ]]; then
    echo "Running docker-compose exec db psql"
    docker-compose exec db psql -U postgres
  elif [[ $# -eq 1 ]]; then
    echo "Running docker-compose exec $1 bash"
    docker-compose exec "$1" bash
  elif [[ $# -eq 0 ]]; then
    local service="$(docker-compose ps --services | fzf)"
    docker-compose exec "$service" bash
  else
    echo "Running docker-compose exec $@"
    docker-compose exec "$@"
  fi
}

# Kubernetes
source <(kubectl completion zsh)
alias k=kubectl
complete -F __start_kubectl k

function db() {
  kubectl port-forward svc/postgres-12-postgresql "4000:5432"
}
function kubesec {
  kubectl get secrets "$1" -o json | jq -r ".data.$2" | base64 --decode
}

# Git
alias gitst="git st"

# GNU sed - brew install gnu-sed
path=("/usr/local/opt/gnu-sed/libexec/gnubin" $path)

# GNU find - brew install findutils
path=("/usr/local/opt/findutils/libexec/gnubin" $path)

# Rails
alias rs=bin/rails
alias rk=bin/rake

# File house-keeping
cleanup() {
  local files="$(find . -name '*.orig')"
  if [[ -z $files ]]; then
    echo "Already neat and tidy"
  else
    find . -name '*.orig' -printf '%p\n' -delete
    echo "The above files were removed successfully"
  fi
}

# iTerm2 Shell Integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh" || true

# GIT FZF
source ~/.oh-my-zsh/custom/git.zsh

# Zsh autosuggestion
bindkey '^ ' autosuggest-accept
